import Layout from "@/components/Layout";
import HomePage from "@/src/Home";
import Head from "next/head";
import Image from "next/image";
import React from "react";

interface Person {
  name: String;
  age?: number;
}

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Microsoft store - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout state="home">
        <HomePage />
      </Layout>
    </>
  );
};

export default Home;
